site_name: HCM US Documentation

-Nautilus:
  -Quem somos: home/quem_somos.md
-Elétrica:
  -Responsabilidades: eletrica/eletrica.md
  -Treinamentos:
    -Placas: eletrica/placas.md

# Repo link + name
repo_url: https://github.com/nautilusufrgs/nautilus.git
repo_name: nautilusufrgs/nautilus
edit_uri: edit/master/docs/
site_url:
use_directory_urls: false

# Configuration
extra_css:
  - stylesheets/custom-colors.css

theme:
  name: material
  custom_dir: custom-assets
  favicon: 013-flag.svg
  icon:
    logo: 013-flag
    repo: fontawesome/brands/github

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    - instant
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
  plugins:
    - search
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
extra:
  social:

markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - def_list
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - assets/.icons
